=== eliansh/DP2-Assignment2/temp165246001/xsd/WFInfo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/WFInfo"
xmlns:tns="http://www.example.org/WFInfo" elementFormDefault="qualified">
<element name="workFlowSystem" type="tns:workFlowSystemType">

	
	
	 <key name="workFlowNameKey">
      <selector xpath="tns:workFlows/tns:workFlow" />
      <field xpath="@flowName" />
    </key>

    <keyref name="relatedWorkFlowKeyRef" refer="tns:workFlowNameKey">
      <selector xpath="tns:workFlows/tns:workFlow/tns:actions/tns:action" />
      <field xpath="@relatedWorkFlow" />
    </keyref>
	
	
	
</element>
    
    
    <complexType name="workFlowSystemType">
    	<sequence>	
    		<element name="workFlows" type="tns:workFlowsType"/>
    	</sequence>
    </complexType>
    
    
    <complexType name="workFlowsType">
    	<sequence>
    		<element name="workFlow" minOccurs="0" maxOccurs="unbounded" type="tns:workFlowType">
    		
    		<key name="actionNameKey">
     		  <selector xpath="tns:actions/tns:action" />
    	      <field xpath="@actionName" />
    		</key>

  		    <keyref name="actionStatNameKeyRef" refer="tns:actionNameKey">
     		 <selector xpath="tns:processes/tns:process/tns:actionStatuses/tns:actionStatus" />
    		  <field xpath="@actionStatName" />
    		 </keyref>
    		</element>
    	</sequence>
    </complexType>
    
    <complexType name="workFlowType">
    	<sequence>
    		<element name="actions" type="tns:actionsType">
    			<unique name="actionNameUnique">
    				<selector xpath="tns:action" />
    				<field xpath="@actionName" />
    			</unique>
    		</element>
    		<element name="processes" type="tns:processesType"></element>
    	</sequence>
		    	
		<attribute name="flowName" use="required" type="tns:nameType"/>
	</complexType>
	
    
    <complexType name="actionsType">
    	<sequence>
    		<element name="action" minOccurs="0" maxOccurs="unbounded" type="tns:actionType"></element>
    	</sequence>
    </complexType>
    
    <simpleType name="nameType">
	    <restriction base="token">
		    	<minLength value="1"></minLength>
		    	<pattern value="[A-Za-z][A-Za-z0-9]*"/>
		</restriction>
    </simpleType>
    
    <simpleType name="roleType">
	    <restriction base="token">
		    		<minLength value="1"></minLength>
		    		<pattern value="[A-Za-z]+"/>
		    	</restriction>
    </simpleType>
    
    <complexType name="actionType">
    	<sequence>
    	    <element name="simpleAct" minOccurs="0" maxOccurs="1" type="tns:simpleActType"></element>
    		<element name="processAct" minOccurs="0" maxOccurs="1" type="tns:processActType"></element>
    	</sequence>
    	<attribute name="actionName" use="required" type="tns:nameType"/>
    	<attribute name="actionRole" use="required" type="tns:roleType"/>
    	<attribute name="automaticallyInstantiated" use="required" type="boolean"/>
    </complexType>
    
    <complexType name="simpleActType">
    	<sequence>
    		<element name="nextAction" minOccurs="0" maxOccurs="unbounded" type="tns:nextActionType"></element>
    	</sequence>
    </complexType>
    
    <complexType name="nextActionType">
    		<attribute name="nextPossibleAction" use="required" type="tns:nameType"/>
    </complexType>
    
    <complexType name="processActType">
    	<attribute name="relatedWorkFlow" use="required" type="tns:nameType"/>
    </complexType>
    
    <complexType name="processesType">
    	<sequence>
    		<element name="process" minOccurs="0" maxOccurs="unbounded" type="tns:processType"></element>
    	</sequence>
    </complexType>
    
     <complexType name="processType">
    	<sequence>
    		<element name="actionStatuses" type="tns:actionStatusesType"></element>
    	</sequence>
    	<attribute name="startTime" use="required" type="dateTime"></attribute>
    </complexType>
    
    <complexType name="actionStatusesType">
    	<sequence>
    		<element name="actionStatus" minOccurs="0" maxOccurs="unbounded" type="tns:actionStatusType"></element>
    	</sequence>
    </complexType>
    
     <complexType name="actionStatusType">
    	<sequence>
    		<element name="actor" minOccurs="0" maxOccurs="1" type="tns:actorType"></element>
    	</sequence>
    	<attribute name="actionStatName" use="required" type="tns:nameType"></attribute>
    	<attribute name="terminated" use="required" type="boolean"></attribute>
    	<attribute name="terminationTime" use="optional" type="dateTime"></attribute>
    	<attribute name="takenInCharge" use="required" type="boolean"></attribute>
    </complexType>
    
    <complexType name="actorType">
    	<attribute name="actorName" use="required" type="string"></attribute>
    	<attribute name="actorRole" use="required" type="string"></attribute>
    </complexType>
    
</schema>

=== eliansh/DP2-Assignment2/xsd/WFInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<workFlowSystem xmlns="http://www.example.org/WFInfo" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/WFInfo WFInfo.xsd">
    <workFlows>
        <workFlow flowName="PrepaidSale">
            <actions>
                <action actionName="InvoiceIssuance" actionRole="Accountingman" automaticallyInstantiated="true">
                    <simpleAct>
                        <nextAction nextPossibleAction="PaymentReception"/>
                    </simpleAct>
                </action>
                <action actionName="PaymentReception" actionRole="Accountingman" automaticallyInstantiated="false">
                    <simpleAct>
                        <nextAction nextPossibleAction="GoodsDelivery"/>
                    </simpleAct>
                </action>
                <action actionName="GoodsDelivery" actionRole="Warehouseman" automaticallyInstantiated="false">
                    <simpleAct/>
                </action>
            </actions>
            <processes>
                <process startTime="2015-10-15T11:32:40.000+02:00">
                    <actionStatuses>
                        <actionStatus actionStatName="InvoiceIssuance" terminated="true" terminationTime="2015-10-16T03:09:40.000+02:00" takenInCharge="true">
                            <actor actorName="Caio Di Noto" actorRole="Accountingman"/>
                        </actionStatus>
                        <actionStatus actionStatName="PaymentReception" terminated="false" takenInCharge="true">
                            <actor actorName="Caio Di Noto" actorRole="Accountingman"/>
                        </actionStatus>
                    </actionStatuses>
                </process>
                <process startTime="2015-10-06T21:04:40.000+02:00">
                    <actionStatuses>
                        <actionStatus actionStatName="InvoiceIssuance" terminated="true" terminationTime="2015-10-08T22:27:40.000+02:00" takenInCharge="true">
                            <actor actorName="Caio Di Noto" actorRole="Accountingman"/>
                        </actionStatus>
                        <actionStatus actionStatName="PaymentReception" terminated="true" terminationTime="2015-10-10T12:15:40.000+02:00" takenInCharge="true">
                            <actor actorName="James Prisco" actorRole="Accountingman"/>
                        </actionStatus>
                        <actionStatus actionStatName="GoodsDelivery" terminated="false" takenInCharge="false"/>
                    </actionStatuses>
                </process>
                <process startTime="2015-11-01T00:30:40.000+01:00">
                    <actionStatuses>
                        <actionStatus actionStatName="InvoiceIssuance" terminated="false" takenInCharge="false"/>
                    </actionStatuses>
                </process>
                <process startTime="2015-10-24T11:23:40.000+02:00">
                    <actionStatuses>
                        <actionStatus actionStatName="InvoiceIssuance" terminated="true" terminationTime="2015-10-25T23:45:40.000+01:00" takenInCharge="true">
                            <actor actorName="James Prisco" actorRole="Accountingman"/>
                        </actionStatus>
                        <actionStatus actionStatName="PaymentReception" terminated="true" terminationTime="2015-10-27T12:47:40.000+01:00" takenInCharge="true">
                            <actor actorName="James Prisco" actorRole="Accountingman"/>
                        </actionStatus>
                        <actionStatus actionStatName="GoodsDelivery" terminated="true" terminationTime="2015-10-28T09:20:40.000+01:00" takenInCharge="true">
                            <actor actorName="Andrew Perla" actorRole="Warehouseman"/>
                        </actionStatus>
                    </actionStatuses>
                </process>
                <process startTime="2015-10-30T06:54:40.000+01:00">
                    <actionStatuses>
                        <actionStatus actionStatName="InvoiceIssuance" terminated="true" terminationTime="2015-10-31T13:38:40.000+01:00" takenInCharge="true">
                            <actor actorName="Caio Di Noto" actorRole="Accountingman"/>
                        </actionStatus>
                        <actionStatus actionStatName="PaymentReception" terminated="true" terminationTime="2015-10-31T16:27:40.000+01:00" takenInCharge="true">
                            <actor actorName="James Prisco" actorRole="Accountingman"/>
                        </actionStatus>
                        <actionStatus actionStatName="GoodsDelivery" terminated="true" terminationTime="2015-11-02T00:30:40.000+01:00" takenInCharge="true">
                            <actor actorName="Andrew Perla" actorRole="Warehouseman"/>
                        </actionStatus>
                    </actionStatuses>
                </process>
            </processes>
        </workFlow>
        <workFlow flowName="NormalSale">
            <actions>
                <action actionName="PaymentReception" actionRole="Accountingman" automaticallyInstantiated="false">
                    <simpleAct/>
                </action>
                <action actionName="InvoiceIssuance" actionRole="Accountingman" automaticallyInstantiated="true">
                    <simpleAct>
                        <nextAction nextPossibleAction="PaymentReception"/>
                    </simpleAct>
                </action>
                <action actionName="GoodsDelivery" actionRole="Warehouseman" automaticallyInstantiated="true">
                    <simpleAct/>
                </action>
            </actions>
            <processes>
                <process startTime="2015-10-27T10:35:40.000+01:00">
                    <actionStatuses>
                        <actionStatus actionStatName="GoodsDelivery" terminated="false" takenInCharge="false"/>
                        <actionStatus actionStatName="InvoiceIssuance" terminated="false" takenInCharge="false"/>
                    </actionStatuses>
                </process>
                <process startTime="2015-10-18T14:53:40.000+02:00">
                    <actionStatuses>
                        <actionStatus actionStatName="GoodsDelivery" terminated="true" terminationTime="2015-10-19T17:34:40.000+02:00" takenInCharge="true">
                            <actor actorName="Henry H La Viola" actorRole="Warehouseman"/>
                        </actionStatus>
                        <actionStatus actionStatName="InvoiceIssuance" terminated="true" terminationTime="2015-10-21T06:26:40.000+02:00" takenInCharge="true">
                            <actor actorName="Paola Garibo" actorRole="Accountingman"/>
                        </actionStatus>
                        <actionStatus actionStatName="PaymentReception" terminated="true" terminationTime="2015-10-22T00:40:40.000+02:00" takenInCharge="true">
                            <actor actorName="Paola Garibo" actorRole="Accountingman"/>
                        </actionStatus>
                    </actionStatuses>
                </process>
                <process startTime="2015-10-10T08:24:40.000+02:00">
                    <actionStatuses>
                        <actionStatus actionStatName="GoodsDelivery" terminated="false" takenInCharge="false"/>
                        <actionStatus actionStatName="InvoiceIssuance" terminated="false" takenInCharge="false"/>
                    </actionStatuses>
                </process>
                <process startTime="2015-10-06T08:50:40.000+02:00">
                    <actionStatuses>
                        <actionStatus actionStatName="GoodsDelivery" terminated="false" takenInCharge="true">
                            <actor actorName="Andrea Balestro" actorRole="Warehouseman"/>
                        </actionStatus>
                        <actionStatus actionStatName="InvoiceIssuance" terminated="false" takenInCharge="true">
                            <actor actorName="Paola Garibo" actorRole="Accountingman"/>
                        </actionStatus>
                    </actionStatuses>
                </process>
            </processes>
        </workFlow>
        <workFlow flowName="SaleManagement">
            <actions>
                <action actionName="AcceptOrder" actionRole="Salesman" automaticallyInstantiated="true">
                    <simpleAct>
                        <nextAction nextPossibleAction="PrepaidSale"/>
                        <nextAction nextPossibleAction="NormalSale"/>
                    </simpleAct>
                </action>
                <action actionName="NormalSale" actionRole="SalesManager" automaticallyInstantiated="false">
                    <processAct relatedWorkFlow="NormalSale"/>
                </action>
                <action actionName="PrepaidSale" actionRole="SalesManager" automaticallyInstantiated="false">
                    <processAct relatedWorkFlow="PrepaidSale"/>
                </action>
            </actions>
            <processes>
                <process startTime="2015-10-22T00:06:40.000+02:00">
                    <actionStatuses>
                        <actionStatus actionStatName="AcceptOrder" terminated="true" terminationTime="2015-10-22T15:02:40.000+02:00" takenInCharge="true">
                            <actor actorName="Henry H Lamarn" actorRole="Salesman"/>
                        </actionStatus>
                        <actionStatus actionStatName="PrepaidSale" terminated="true" terminationTime="2015-10-24T03:41:40.000+02:00" takenInCharge="true">
                            <actor actorName="Carol Li Ming" actorRole="SalesManager"/>
                        </actionStatus>
                    </actionStatuses>
